update at Sun  5 Apr 2026 17:24:00 CST

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -59,6 +59,21 @@ else
 git commit -m "update at `date`"
 fi
 
+# 添加云服务器源
+echo "**************PUSH TO CLOUD BEGIN**************"
+# 改变云服务器 remote url
+git remote add cloud git@81.70.132.212:/home/git/hexo.git
+# 提交博客内容
+git push -u cloud master -f
+
+if [ $? != 0 ]
+then
+echo "**************PUSH TO CLOUD FAILED**************"
+exit 1
+else
+echo "**************PUSH TO CLOUD SUCCESS**************"
+fi
+
 # 添加 github 源
 echo "**************PUSH TO GITHUB BEGIN**************"
 # 改变 github remote url
@@ -73,17 +88,6 @@ exit 1
 else
 echo "**************PUSH TO GITHUB SUCCESS**************"
 fi
-
-# 添加云服务器源（已停用，如需恢复请取消注释）
-# echo "**************PUSH TO CLOUD BEGIN**************"
-# git remote add cloud git@81.70.132.212:/home/git/hexo.git
-# git push -u cloud master -f
-# if [ $? != 0 ]
-# then
-# echo "**************PUSH TO CLOUD FAILED**************"
-# else
-# echo "**************PUSH TO CLOUD SUCCESS**************"
-# fi
 
 cd -
 
